### ISSUE TITLE
Nonexistent Paths

### ISSUE THREAD

**Issue by ajmassi** [ajmassi/wg-discord#4]
## Description
Currently throws error if the path does not exist for:
- wireguard_config_path
- wireguard_user_config_dir

## Acceptance Criteria:
Add path existence checks at on config parse

**Comment by abefleming** [comment]
Add path existence checks in the model through validator

**Comment by abefleming** [comment]
Looks like usage of type `FieldPath` and `DirectoryPath` already perform existence checks, and validates that the target is a file or directory (source: https://docs.pydantic.dev/usage/types/#pydantic-types). Addition of new validators is redundant here. Moving to close the issue.
