### ISSUE TITLE
Filepath rewrite in wgconfig

### ISSUE THREAD

**Issue by ajmassi** [ajmassi/wg-discord#6]
## Description
file2filename() from [wgconfig](https://github.com/towalink/wgconfig/blob/master/src/wgconfig/__init__.py) might create some issues for non-"/etc/wireguard/" locations

## Acceptance Criteria
* Determine if this is an issue worth addressing
* Implement remedy (if required)

**Comment by abefleming** [comment]
Shouldn't be an issue. README shows that an interface, filename, or file path can be provided. We should be able to just pass in `wireguard_config_path`  from the config. (Methods for Interaction: https://github.com/towalink/wgconfig#methods-for-interaction) 
Looking at the code for `file2filename()`, if you pass a filename where `file = "wg0.conf"` then it will attempt to create a file path with the default of `/etc/wireguard`. However, if you pass in a file path where `file = /my/custom/config/path/to/wg0.conf` then `if os.path.basename(file) == file:` evaluates to `False` and will just return back the file path.

**Comment by abefleming** [comment]
Snippet from IDLE for visual 
```
>>> import os
>>> os.path.basename("/etc/wireguard/wg0.conf") == "/etc/wireguard/wg0.conf"
False
>>> os.path.basename("wg0.conf") == "wg0.conf"
True
>>>
```
